development:
  adapter: postgresql
  encoding: unicode
  database: merry_bright_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: merry_bright_test
  pool: 5
  host: localhost

